title: Ganesh Rajendra Kadam # your name (or website title) here
logo: "/profile.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
 IT Network Administrator
  <br><br>
  <a href="mailto:ganeshkadam2899@gmail.com">ganeshkadam2899@gmail.com </a>
  <br>
  <a href="https://www.linkedin.com/in/ganesh-kadam-aa5621166">LinkedIn Profile</a>
  <br>
  <a href="https://sergiogk.github.io/">Gihub</a> 
  
  
  
theme: jekyll-theme-minimal
